[toolchain]
# https://rust-lang.github.io/rustup-components-history/aarch64-apple-darwin.html
channel = "nightly-2023-05-31"
components = [ "rustfmt", "clippy", "cargo", "llvm-tools-preview", "wasm32-unknown-unknown" ]
