name: 'Setup Repo Action'
description: 'A reusable composite action that setups rust and other common tasks'
inputs:
  toolchain:
    description: 'An example input parameter'
    required: false
    default: 'nightly-2023-05-02'

runs:
  using: 'composite'
  steps:
    - name: Install nightly
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: "rustfmt,clippy,cargo,llvm-tools-preview"
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
