[package]
name = "trading-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.wrokspace = true
rust_decimal.wrokspace = true
chrono.wrokspace = true
