on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: deploy
jobs:
  deploy:
    runs-on: ubuntu-22.04
    name: deploy
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Update apt
        run: sudo apt update

      - name: Setup repo
        uses: ./.github/actions/setup-repo
        with:
          targets: wasm32-unknown-unknown

      - name: cargo build
        run: cargo make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_API_KEY }}
          password: ${{ secrets.DO_API_KEY }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./server/Dockerfile
          tags: registry.digitalocean.com/riive-home/trading-view:latest
